### ISSUE TITLE
Palestra sobre React e Componentização

### ISSUE THREAD

**Issue by felipeorlando** [FocusMeetups/sugestoes#13]
**Tema:** React e Componentização
**Breve descrição:** Gostaria de falar sobre o pouco que aprendi de React e o porque componentização também é assunto de UX.
**Data:** Indefinida

**Comment by danilovaz** [comment]
@felipeorlando E essa palestra aí? :smile:

**Comment by felipeorlando** [comment]
Vai ficar pra história. rs

**Comment by danilovaz** [comment]
Like so many things 🤣
